version: "3.8"
services:
  db:
    container_name: "scribe-app-db"
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "scribe-db"
      POSTGRES_USER: "scribe-app"
      POSTGRES_PASSWORD: "secret"