CREATE TABLE IF NOT EXISTS t_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    u_name VARCHAR(255) NOT NULL,
    u_email VARCHAR(512) NOT NULL,
    u_password VARCHAR(512) NOT NULL,
    CONSTRAINT pk_t_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_t_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS t_users_roles (
    user_id BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_t_users_roles PRIMARY KEY (user_id, roles_id),
    CONSTRAINT fk_user_id_on_tusers FOREIGN KEY (user_id) REFERENCES t_users (id),
    CONSTRAINT fk_roles_id_on_troles FOREIGN KEY (roles_id) REFERENCES t_roles (id)
);